server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://81.70.10.9:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Diao0707
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource # 自定义数据源
    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 81.70.10.9 # Redis服务器地址
    database: 0
    port: 6379
    password: Diao0707

redis:
  key:
    expire:
      authCode: 120 #过期时间120秒
    prefix:
      authCode: "portal:authCode:"

mybatis-plus.configuration.log-impl:
  org.apache.ibatis.logging.stdout.StdOutImpl

swagger: true


# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: fddc1534226xxxxxb4594dc5sd56a41s #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头